[package]
name = "fedimint-empty-common"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimint-empty is a empty fedimint module, good template for a new module."
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "fedimint_empty_common"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
fedimint-core = { version = "=0.4.0-alpha", path = "../../fedimint-core" }
serde = { workspace = true }
thiserror = { workspace = true }
