[package]
name = "fedimint-tbs"
version = "0.4.0-alpha"
authors = ["The Fedimint Developers"]
edition = "2021"
description = "tbs is a helper cryptography library for threshold blind signatures"
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/fedimint/fedimint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
unstable = []

[lib]
name = "tbs"
path = "src/lib.rs"

[dependencies]
fedimint-core = { version = "=0.4.0-alpha", path = "../../fedimint-core/" }
bls12_381 = { workspace = true }
group = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true }
sha3 = "0.10.8"

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "tbs"
harness = false
